/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf 
Author: EverZax (https://sketchfab.com/EverZax)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sci-fi-football-17c6b1572eb04e61b7af7bead62704df
Title: Sci-Fi Football
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/scene.gltf");

  const meshRef = useRef();

  // Rotate the model on every frame
  useFrame(() => {
    if (meshRef.current) {
      meshRef.current.rotation.y += 0.01; // Adjust speed here
    }
  });

  return (
    <group {...props} dispose={null} ref={meshRef}>
      <group scale={0.14}>
        <mesh
          geometry={nodes["Sci-Fi_Football_Sci-Fi_Football_0"].geometry}
          material={materials["Sci-Fi_Football"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/scene.gltf");
